// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteChat(arg1) {
  return window['go']['main']['App']['DeleteChat'](arg1);
}

export function GetChat(arg1) {
  return window['go']['main']['App']['GetChat'](arg1);
}

export function GetChatMessages(arg1) {
  return window['go']['main']['App']['GetChatMessages'](arg1);
}

export function GetChats() {
  return window['go']['main']['App']['GetChats']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetUserId() {
  return window['go']['main']['App']['GetUserId']();
}

export function GetUsername() {
  return window['go']['main']['App']['GetUsername']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InitChatFromInitializer(arg1) {
  return window['go']['main']['App']['InitChatFromInitializer'](arg1);
}

export function InitChatFromReceiver(arg1) {
  return window['go']['main']['App']['InitChatFromReceiver'](arg1);
}

export function IsSignedUp() {
  return window['go']['main']['App']['IsSignedUp']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function PullNotificationsAndUpdateData() {
  return window['go']['main']['App']['PullNotificationsAndUpdateData']();
}

export function RenameChat(arg1, arg2) {
  return window['go']['main']['App']['RenameChat'](arg1, arg2);
}

export function SearchByUsername(arg1) {
  return window['go']['main']['App']['SearchByUsername'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}

export function SetUsernameConfig(arg1, arg2) {
  return window['go']['main']['App']['SetUsernameConfig'](arg1, arg2);
}

export function SignUp(arg1) {
  return window['go']['main']['App']['SignUp'](arg1);
}

export function TryRequestChat(arg1) {
  return window['go']['main']['App']['TryRequestChat'](arg1);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}
