// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {data} from '../models';
import {messenger_client} from '../models';

export function DeleteChat(arg1:number):Promise<void>;

export function GetChat(arg1:number):Promise<data.Chat>;

export function GetChatMessages(arg1:number):Promise<Array<data.Message>>;

export function GetChats():Promise<Array<data.Chat>>;

export function GetState():Promise<string>;

export function GetUserId():Promise<number>;

export function GetUsername():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function InitChatFromInitializer(arg1:number):Promise<data.Chat>;

export function InitChatFromReceiver(arg1:number):Promise<data.Chat>;

export function IsSignedUp():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function PullNotificationsAndUpdateData():Promise<Array<messenger_client.WebNotificationWithTypeInfo>>;

export function RenameChat(arg1:number,arg2:string):Promise<void>;

export function SearchByUsername(arg1:string):Promise<number>;

export function SendMessage(arg1:number,arg2:string):Promise<data.Message>;

export function SetUsernameConfig(arg1:string,arg2:boolean):Promise<void>;

export function SignUp(arg1:string):Promise<void>;

export function TryRequestChat(arg1:string):Promise<data.Chat>;

export function Unlock(arg1:string):Promise<void>;
